version: '3.9'

services:
  db-pg:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.prod

  web-app:
    build:
      context: ./app
      dockerfile: Dockerfile_prod
    command: gunicorn core_module.wsgi:application --bind 0.0.0.0:8000
    ports:
      - 8080:8000
    env_file:
      - ./.env.prod
    depends_on:
      - db-pg

volumes:
  postgres_data: